package controller

import (
	"context"
	"fmt"

	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"kdex.dev/web/internal"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func (r *KDexInternalHostReconciler) indexers(mgr ctrl.Manager) error {
	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexFunction{}, internal.AUTOGENERATED_INDEX_KEY, func(rawObj client.Object) []string {
		fn := rawObj.(*kdexv1alpha1.KDexFunction)
		return []string{fmt.Sprintf("%v", fn.Spec.Metadata.AutoGenerated)}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexFunction{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		fn := rawObj.(*kdexv1alpha1.KDexFunction)
		if fn.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{fn.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexInternalTranslation{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		translation := rawObj.(*kdexv1alpha1.KDexInternalTranslation)
		if translation.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{translation.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexPageBinding{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		pageBinding := rawObj.(*kdexv1alpha1.KDexPageBinding)
		if pageBinding.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{pageBinding.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexRole{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		scopeBinding := rawObj.(*kdexv1alpha1.KDexRole)
		if scopeBinding.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{scopeBinding.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexInternalUtilityPage{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		up := rawObj.(*kdexv1alpha1.KDexInternalUtilityPage)
		if up.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{up.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexRoleBinding{}, internal.HOST_INDEX_KEY, func(rawObj client.Object) []string {
		scopeBinding := rawObj.(*kdexv1alpha1.KDexRoleBinding)
		if scopeBinding.Spec.HostRef.Name == "" {
			return nil
		}
		return []string{scopeBinding.Spec.HostRef.Name}
	}); err != nil {
		return err
	}

	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kdexv1alpha1.KDexRoleBinding{}, internal.SUB_INDEX_KEY, func(rawObj client.Object) []string {
		scopeBinding := rawObj.(*kdexv1alpha1.KDexRoleBinding)
		if scopeBinding.Spec.Subject == "" {
			return nil
		}
		return []string{scopeBinding.Spec.Subject}
	}); err != nil {
		return err
	}

	return nil
}
