package internal

const (
	BACKEND                 = "backend"
	AUTOGENERATED_INDEX_KEY = "spec.metadata.autoGenerated"
	HOST_INDEX_KEY          = "spec.hostRef.name"
	SUB_INDEX_KEY           = "spec.Subject"
	OCI_IMAGE               = "oci-image"
	PAGE_BINDING_FINALIZER  = "kdex.dev/kdex-web-page-binding-finalizer"
	TRANSLATION_FINALIZER   = "kdex.dev/kdex-web-translation-finalizer"
)
