package internal

import "k8s.io/apimachinery/pkg/runtime/schema"

const (
	AUTOGENERATED_INDEX_KEY = "spec.metadata.autoGenerated"
	BACKEND                 = "backend"
	HOST_INDEX_KEY          = "spec.hostRef.name"
	OCI_IMAGE               = "oci-image"
	PAGE_BINDING_FINALIZER  = "kdex.dev/kdex-web-page-binding-finalizer"
	SHARED_VOLUME           = "shared-volume"
	SUB_INDEX_KEY           = "spec.subject"
	TRANSLATION_FINALIZER   = "kdex.dev/kdex-web-translation-finalizer"
	WORKDIR                 = "/shared"
)

var KPackImageGVK = schema.GroupVersionKind{
	Group:   "kpack.io",
	Version: "v1alpha2",
	Kind:    "Image",
}
